# before_script:
#     - apt-get install maven

stages:
    - test
    - lint
    - coverage

# cache maven repo
# variables:
#   MAVEN_OPTS: -Dmaven.repo.local=/cache/maven.repository

java-tests:
    image: maven:latest
    stage: test
    script:
        - mvn test -PskipAngular

java-lint:
    image: maven:latest
    stage: lint
    script:
        - mvn pmd:check

java-coverage:
    image: maven:latest
    stage: coverage
    script:
        - mvn jacoco:prepare-agent install jacoco:report -PskipAngular

angular-lint:
    image: node:latest
    stage: lint
    script:
        - cd ui/src/main/resources/frontend && npm install && ./node_modules/@angular/cli/bin/ng lint

# angular-test:
#     image: node:latest
#     stage: test
#     script:
#         - cd ui/src/main/resources/frontend && npm install && ./node_modules/@angular/cli/bin/ng test