stages:
    - build
    - test

variables:
  MAVEN_OPTS: -Dmaven.repo.local=/cache/maven.repository  # cache maven repo for faster builds

java-build:
    image: maven:3.6.0-jdk-11
    stage: build
    script:
        - mvn package -PskipAngular -DskipTests


java-tests:
    image: maven:3.6.0-jdk-11
    stage: test
    script:
        - mvn test -PskipAngular

java-lint:
    image: maven:3.6.0-jdk-11
    stage: test
    script:
        - mvn pmd:check

java-coverage:
    image: maven:3.6.0-jdk-11
    stage: test
    script:
        - mvn jacoco:prepare-agent install jacoco:report -PskipAngular

angular-build:
    image: node:12-alpine
    stage: build
    script:
        - cd ui/src/main/resources/frontend && npm install && npm run build -- --prod

angular-lint:
    image: node:12-alpine
    stage: test
    script:
        - cd ui/src/main/resources/frontend && npm install && npm run lint

angular-tests:
    image: circleci/node:12-browsers
    stage: test
    script:
        - cd ui/src/main/resources/frontend && npm install && npm run test