# before_script:
#     - apt-get install maven

stages:
    - test
    - lint

java-tests:
    image: maven:latest
    stage: test
    script:
        - mvn test

java-lint:
    image: maven:latest
    stage: lint
    script:
        - mvn pmd:check

angular:
    image: node:latest
    stage: lint
    script:
        - cd ui/src/main/resources/frontend && npm install && ./node_modules/@angular/cli/bin/ng lint